[theme]
primaryColor = "#FF0000"               # Red for primary elements
backgroundColor = "#FFFFFF"            # White background
secondaryBackgroundColor = "#F0F0F0"   # Light gray for secondary areas
textColor = "#000000"                  # Black text
font = "sans serif"